stages:
  - scan

sast:
  stage: scan
  image: rust:1.72
  before_script:
    - apt-get update && apt-get install -y curl
    - rustup component add cargo-audit || true
    - cargo install cargo-audit --force
  script:
    - cargo generate-lockfile || true
    - cargo audit --json > gl-sast-report.json || echo '{}' > gl-sast-report.json
  artifacts:
    paths:
      - gl-sast-report.json
    reports:
      sast: gl-sast-report.json
  allow_failure: false
  extends: .scheduled_weekly

dependency_scanning:
  stage: scan
  image: rust:1.72
  before_script:
    - apt-get update && apt-get install -y curl
    - rustup component add cargo-audit || true
    - cargo install cargo-audit --force
  script:
    - cargo generate-lockfile || true
    - cargo audit --json > gl-dependency-scanning-report.json || echo '{}' > gl-dependency-scanning-report.json
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  allow_failure: false
  extends: .scheduled_weekly

.scheduled_weekly:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never

