# GitLab CI: Secure Stage for Rust (SAST + Dependency Scanning)

stages:
  - scan

sast:
  stage: scan
  variables:
    SAST_EXCLUDED_PATHS: "tests/,target/,examples/"
    SAST_INCLUDE_PATHS: "src/"
    SAST_ANALYZER_IMAGE: "registry.gitlab.com/gitlab-org/security-products/analyzers/cargo-audit:latest"
  artifacts:
    paths:
      - gl-sast-report.json
    reports:
      sast: gl-sast-report.json
  allow_failure: false

dependency_scanning:
  stage: scan
  image: rust:1.72
  before_script:
    - apt-get update -y && apt-get install -y curl
    - rustup component add cargo-audit || true
    - cargo install cargo-audit --force
  script:
    - cargo generate-lockfile || true
    - cargo audit --json > gl-dependency-scanning-report.json || echo '{}' > gl-dependency-scanning-report.json
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json
  allow_failure: false
